<a href="https://colab.research.google.com/github/anakhabose/Learn.py/blob/main/TASK_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Generate a 3 x 3 matrix using random module.

In [1]:
#please provide your answer below this line.
import numpy as np
a = np.random.rand(3,3)
print(a)

[[0.5805743  0.54180854 0.23882762]
 [0.41857793 0.62007167 0.37954026]
 [0.92093798 0.1285588  0.47463393]]


2. Generate two 4 x 4 matrix using numpy and 

 a) Reshape it to 2 x 8matrix and vertically stack it.

 b) Reshape it to 2 x 8 matrix and horizontally stack it.

In [28]:
#please provide your answer below this line.
import numpy as np
a= np.random.rand(4,4)
print('i)',a)
b = np.random.rand(4,4)
print(b)
a = a.reshape(2,8)
b = b.reshape(2,8)
print('ii)',a)
print(b)
print('iii)',np.vstack((a,b)))
print('iv)',np.hstack((a,b)))

i) [[0.02628413 0.93366486 0.6397602  0.8599104 ]
 [0.51689807 0.13365716 0.60478884 0.05285271]
 [0.95732667 0.01772421 0.98425818 0.33115396]
 [0.67927717 0.60252078 0.49004483 0.95464018]]
[[0.7661929  0.68216255 0.17677254 0.65904663]
 [0.34352966 0.71086441 0.66273901 0.83770375]
 [0.79900057 0.28536057 0.07595509 0.18278372]
 [0.4070026  0.47578737 0.56082126 0.25612247]]
ii) [[0.02628413 0.93366486 0.6397602  0.8599104  0.51689807 0.13365716
  0.60478884 0.05285271]
 [0.95732667 0.01772421 0.98425818 0.33115396 0.67927717 0.60252078
  0.49004483 0.95464018]]
[[0.7661929  0.68216255 0.17677254 0.65904663 0.34352966 0.71086441
  0.66273901 0.83770375]
 [0.79900057 0.28536057 0.07595509 0.18278372 0.4070026  0.47578737
  0.56082126 0.25612247]]
iii) [[0.02628413 0.93366486 0.6397602  0.8599104  0.51689807 0.13365716
  0.60478884 0.05285271]
 [0.95732667 0.01772421 0.98425818 0.33115396 0.67927717 0.60252078
  0.49004483 0.95464018]
 [0.7661929  0.68216255 0.17677254 0.65904663 0.34