<a href="https://colab.research.google.com/github/anakhabose/Learn.py/blob/main/TASK_13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Create a 3x3 array values ranging from 0-8.Find the sum of the elements in this array.

In [56]:
#please enter your code below this line.
import numpy as np
A= np.arange(9).reshape(3,3)
print(A)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [57]:
#sum
x= A.sum()
print(x)

36


2. Create a 3x3 array values ranging from 0-8.Find the row sum and column sum of this array.

In [58]:
#please enter your code below this line.
import numpy as np
B= np.arange(9).reshape(3,3)
print(B)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [60]:
y=A.sum(axis=1)
print('rows sum:',y)
z= A.sum(axis=0)
print('column sum:',z)

rows sum: [ 3 12 21]
column sum: [ 9 12 15]


3. Create a 4x4 array values ranging from 0-15. Now,

    a) Find the mininmum value in the array.
    
    b) Find the maximum value in the array.

    c) Find the mean of the values in the array.

In [61]:
#please enter your code belowthis line.
import numpy as np
C= np.arange(16).reshape(4,4)
print(C)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [62]:
u= C.min()
print('Minimum=',u)
v= C.max()
print('Maximum=',v)
w= C.mean()
print('Mean=',w)

Minimum= 0
Maximum= 15
Mean= 7.5


4. Create an 10x10 array values ranging from 0-99.And ,

    a) Print the 7th row.
    
    b) Print the rows from 4-8.

    c) Print the value at the index 5,5.

    d) Print the 5th colomn.

    e) Print the columns from 2-5.

In [63]:
#please enter your code below this line.
D= np.arange(100).reshape(10,10)
print(D)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [68]:
p= D[6,:]
print('7th row:',p)
 
q= D[3,:],D[4,:],D[5,:],D[6,:],D[7,:]
print('Rows from 4-8',q)
 
r= D[4,4]
print('Index 5,5:',r)
 
s= D[:, 4]
print('5th column',s)
 
t=D[:,1],D[:,2],D[:,3],D[:,4]
print('columns from 2-5:',t)

7th row: [60 61 62 63 64 65 66 67 68 69]
Rows from 4-8 (array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39]), array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49]), array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59]), array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69]), array([70, 71, 72, 73, 74, 75, 76, 77, 78, 79]))
Index 5,5: 44
5th column [ 4 14 24 34 44 54 64 74 84 94]
columns from 2-5: (array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), array([ 2, 12, 22, 32, 42, 52, 62, 72, 82, 92]), array([ 3, 13, 23, 33, 43, 53, 63, 73, 83, 93]), array([ 4, 14, 24, 34, 44, 54, 64, 74, 84, 94]))
