<a href="https://colab.research.google.com/github/anakhabose/Learn.py/blob/main/TASK_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Generate two  3 x 3 matrix and find it's dot product and take the transpose of the answer.

In [14]:
#please provide your answer below this line.
import numpy as np

In [15]:
a = np.random.rand(3,3)
b= np.random.rand(3,3)
print(a)
print(b)

[[0.74602184 0.03095632 0.69630949]
 [0.65106687 0.42673843 0.34556106]
 [0.62019697 0.41309123 0.15739674]]
[[0.63290303 0.09976076 0.22839048]
 [0.6604221  0.952349   0.0704437 ]
 [0.84884872 0.54967762 0.22713554]]


In [17]:
x = np.dot(a,b)
print(x)

[[1.08366514 0.48665067 0.33072159]
 [0.98721875 0.66130203 0.25724771]
 [0.79894514 0.54179581 0.20649715]]


In [18]:
x.transpose()

array([[1.08366514, 0.98721875, 0.79894514],
       [0.48665067, 0.66130203, 0.54179581],
       [0.33072159, 0.25724771, 0.20649715]])

2. Create a 3x3 matrix with elements [55,25,15], [30,44,2], [11,45,77] . Now find the determinant of the given matrix.

In [21]:
#please provide your answer below this line.
import numpy as np
y = np.array([ [55,25,15], [30,44,2], [11,45,77] ])
print(y)

[[55 25 15]
 [30 44  2]
 [11 45 77]]


In [22]:
np.linalg.det(y)

137180.0000000001